### ISSUE TITLE
The author and works menus

### ISSUE THREAD

**Issue by jonathanwestin** [gu-gridh/litteraturlabbet-frontend#16]
When in the text-reuse module, filter out all authors and works that have no text-reuse.

o Make flag in database for these authors – Aram
o Get list of authors – David
o Flag these authors in database – David
o Display list of authors in frontend – Kristin (with help of Jonathan)

**Comment by jonathanwestin** [comment]
Some sort of flag needs to be implemented in the backend that the frontend can check.

**Comment by siskahumlesjo** [comment]
o	Make flag in database for these authors – Aram
o	Get list of authors – David
o	Flag these authors in database – David 
o	Display list of authors in frontend – Kristin (with help of Jonathan)
