### ISSUE TITLE
Top-10 authors, works, and passages for reuse

### ISSUE THREAD

**Issue by jonathanwestin** [gu-gridh/litteraturlabbet-frontend#19]
When first clicking on the reuse module, without yet having made a search, it would benefit the user to see a generated list of top authors, works and passages (10 for each ranked from most to least) in the reuse module.

**Comment by siskahumlesjo** [comment]
David will extract the data. Kristin will implement the lists.

**Comment by kikkipedia** [comment]
Logic is done, but need some css styling
