### ISSUE TITLE
Word embedding

### ISSUE THREAD

**Issue by siskahumlesjo** [gu-gridh/litteraturlabbet-frontend#49]
Timeline: Start working in September
Internal demo: Beginning October

**Comment by daalft** [comment]
Word embeddings will most probably not be used because it's not applicable to such small data. We may consider another approach such as word co-occurrence using techniques such as PPMI/PMI.

**Comment by jroxendal** [comment]
It might interest you to know that 300 dimension word embeddings are already calculated by me for every book in LB and can be found under the key `content_vector`:
https://red.litteraturbanken.se/api/get_work_info?authorid=ZachrissonW&titlepath=BoktryckeriKalender1921

**Comment by daalft** [comment]
Interesting @jroxendal but this is one embedding per book, to find similar books, right? We were thinking about findings word in books.
