### ISSUE TITLE
Search options bug

### ISSUE THREAD

**Issue by siskahumlesjo** [gu-gridh/litteraturlabbet-frontend#53]
Search options:
Fix bug for Augustin berg to show reused list and check for other authors as well

**Comment by jonathanwestin** [comment]
I don't understand this bug report. What is not working as expected?

**Comment by daalft** [comment]
I do not understand either

**Comment by jonathanwestin** [comment]
I think "Augustin Berg" should be August Strindberg...
Ah now I know: it is the same bug as issue 69 that you have fixed!
