### ISSUE TITLE
Order the author menus so all the greyed out authors come below those with reuses

### ISSUE THREAD

**Issue by siskahumlesjo** [gu-gridh/litteraturlabbet-frontend#54]
Move authors without reuse to end of list

**Comment by jonathanwestin** [comment]
This concerns the menu with the authors.

**Comment by daalft** [comment]
Done but only works for text reuse. Needs adapting for gallery

**Comment by daalft** [comment]
Now also works when switching to gallery (but gallery may need a different list of greyed-out authors; but that functionality is easy to add now).
