### ISSUE TITLE
List what works are included in a search

### ISSUE THREAD

**Issue by siskahumlesjo** [gu-gridh/litteraturlabbet-frontend#55]
Add list of reused works information like: short title, author, imprint year

**Comment by jonathanwestin** [comment]
In essence: when two authors have been named, switch the works menu to a menu that displays the list of all the works of these two authors.

**Comment by daalft** [comment]
All the works or only reuse works? I have something which  lists authors and works for one author, it lists all works where reuse has been found chronologically. Could possibly be reused?

![image](https://github.com/gu-gridh/litteraturlabbet-frontend/assets/1140987/204b0e1e-ac99-4bfc-965d-61ac79a32d4f)

**Comment by jonathanwestin** [comment]
Yes, perhaps it can go into the left pane under the work-counter? Or be integrated into the works menu?

**Comment by daalft** [comment]
Only implemented on the cluster overview page. For two authors, we show the reuses directly, so I think it it makes no sense to also include that information there.
