### ISSUE TITLE
Search results sorting

### ISSUE THREAD

**Issue by siskahumlesjo** [gu-gridh/litteraturlabbet-frontend#58]
Add option to switch between chronological sorting and A-Z sorting when searching for authors

**Comment by jonathanwestin** [comment]
To be more precise: this concerns the order of the search results in the view that appears after one has clicked on a certain reuse and then gets a list showing the same phrase in several works. Currently we have that list in chronological author (as per their wish), but if possible they would like to give the reader the choice to sort by author name. See picture below for suggestion where to place that interface element.

![Skärmavbild 2023-10-28 kl  20 30 19 kopiera](https://github.com/gu-gridh/litteraturlabbet-frontend/assets/70022179/073eb46c-4f29-4afb-a2bd-e172bed6cd03)

**Comment by daalft** [comment]
Functionality added but it's ugly.
