### ISSUE TITLE
use LB primary color

### ISSUE THREAD

**Issue by jroxendal** [gu-gridh/litteraturlabbet-frontend#72]
`#7A1400`

**Comment by daalft** [comment]
@jonathanwestin is this the one we are using?

**Comment by jonathanwestin** [comment]
nope. we are using a lighter version but I can see if we can make variations based on this one (we would need light and dark versions anyway to account for hover and various font weights.

**Comment by jonathanwestin** [comment]
Since we are using it in a different way than LB, as backgrounds for buttons and such, I had to light it up a bit. However, the same relations between the red, green and blue channels are kept.
