### ISSUE TITLE
Caption of images

### ISSUE THREAD

**Issue by siskahumlesjo** [gu-gridh/litteraturlabbet-frontend#95]

**Comment by siskahumlesjo** [comment]
About 10 working days. Late August earliest.

**Comment by siskahumlesjo** [comment]
Ash will sen a list of wording to SIska. Will also discuss changes of database tables with Aram.

**Comment by ashely-ra** [comment]
Tags added to images using [RAM model](https://huggingface.co/spaces/xinyu1205/recognize-anything)
